name: super_native_extensions
description: Low level interface various native APIs such as clipboard and Drag and Drop. Not meant to be used directly.
version: 0.9.1
homepage: https://github.com/superlistapp/super_native_extensions

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  # https://pub.dev/packages/meta
  meta: ^1.17.0
  # https://pub.dev/packages/ffi
  ffi: ^2.1.4
  # https://pub.dev/packages/collection
  collection: ^1.19.1
  # https://pub.dev/packages/path
  path: ^1.9.1
  # https://pub.dev/packages/uuid
  uuid: ^4.5.2
  # https://pub.dev/packages/irondash_engine_context
  irondash_engine_context: ^0.5.5
  # https://pub.dev/packages/irondash_message_channel
  irondash_message_channel: ^0.7.0
  # https://pub.dev/packages/device_info_plus
  device_info_plus: ^12.3.0
  # https://pub.dev/packages/pixel_snap
  pixel_snap: ^0.1.5
  # https://pub.dev/packages/web
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.superlist.super_native_extensions
        pluginClass: SuperNativeExtensionsPlugin
      ios:
        pluginClass: SuperNativeExtensionsPlugin
      linux:
        pluginClass: SuperNativeExtensionsPlugin
      macos:
        pluginClass: SuperNativeExtensionsPlugin
      windows:
        pluginClass: SuperNativeExtensionsPluginCApi
      web:
        pluginClass: SuperNativeExtensionsWeb
        fileName: super_native_extensions_web.dart
